name: learning
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - scipy
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - pip:
    - casadi
    - tensorflow
    - stable-baselines3
    - -e /home/john/Documents/master-thesis/code/
